const fs = require("fs");
const path = require("path");

const openapiPath = path.resolve(__dirname, "..", "openapi.yaml");
const content = fs.readFileSync(openapiPath, "utf8");

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

const requiredPaths = [
  "/api/health",
  "/api/auth/me",
  "/api/auth/login",
  "/api/auth/logout",
  "/api/auth/refresh",
  "/api/admin/auth/login",
  "/api/admin/auth/logout",
  "/api/admin/auth/refresh",
  "/api/me",
  "/api/config",
  "/api/home",
  "/api/products",
  "/api/products/{productId}",
  "/api/points-exchange",
  "/api/member/subscribe",
  "/api/orders",
  "/api/orders/{orderId}/pay",
  "/api/payments",
  "/api/orders/{orderId}/payments",
  "/api/payments/{payNo}/mock-callback",
  "/api/payments/{payNo}/lfwin",
  "/api/payments/{payNo}/lfwin/query",
  "/api/payments/{payNo}/lfwin/close",
  "/api/payment-providers/lfwin/notify",
  "/api/orders/{orderId}/refunds",
  "/api/tasks",
  "/api/task-types",
  "/api/task-platform/status",
  "/api/tasks/{taskId}",
  "/api/tasks/{taskId}/submit",
  "/api/submissions",
  "/api/submissions/{submissionId}",
  "/api/task/callback",
  "/api/invite/info",
  "/api/invite/list",
  "/api/invite/stats",
  "/api/signin/status",
  "/api/signin/start",
  "/api/signin/ad_complete",
  "/api/signin/lottery_spin",
  "/api/pickup-sites",
  "/api/delivery/teams",
  "/api/addresses",
  "/api/addresses/{addressId}",
  "/api/withdrawals",
  "/api/points-ledger",
  "/api/ranking",
  "/api/tickets",
  "/api/admin/auth/me",
  "/api/admin/summary",
  "/api/admin/orders",
  "/api/admin/orders/{orderId}/pickup-verify",
  "/api/admin/orders/{orderId}/ship",
  "/api/admin/orders/{orderId}/deliver",
  "/api/admin/products",
  "/api/admin/products/{productId}",
  "/api/admin/inventory-ledger",
  "/api/admin/config",
  "/api/admin/task-submissions",
  "/api/admin/task-submissions/{submissionId}/approve",
  "/api/admin/task-submissions/{submissionId}/reject",
  "/api/admin/users",
  "/api/admin/addresses",
  "/api/admin/invites",
  "/api/admin/users/{userId}",
  "/api/admin/tickets",
  "/api/admin/tickets/{ticketId}",
  "/api/admin/pickup-sites",
  "/api/admin/pickup-sites/{siteId}",
  "/api/admin/delivery-teams",
  "/api/admin/delivery-teams/{teamId}",
  "/api/admin/withdrawals",
  "/api/admin/withdrawals/{withdrawalId}/approve",
  "/api/admin/withdrawals/{withdrawalId}/reject",
  "/api/admin/order-status-logs",
  "/api/admin/operation-logs",
  "/api/admin/approval-requests",
  "/api/admin/approval-requests/{approvalId}/approve",
  "/api/admin/approval-requests/{approvalId}/reject",
  "/api/admin/ledger",
  "/api/admin/payments/cancel-timeouts",
  "/api/admin/delivery/scan-exceptions",
  "/api/admin/permissions",
  "/api/admin/exceptions",
  "/api/admin/exceptions/{exceptionId}/resolve",
  "/api/admin/refunds",
  "/api/admin/refunds/{refundId}/approve"
];

for (const apiPath of requiredPaths) {
  assert(content.includes(`  ${apiPath}:`), `OpenAPI missing path: ${apiPath}`);
}

const requiredTerms = [
  "openapi: 3.0.3",
  "UserBearerAuth",
  "AdminBearerAuth",
  "bearerFormat: HMAC",
  "scheme: bearer",
  "/api/auth/logout",
  "/api/admin/auth/logout",
  "session revoked",
  "pure_points",
  "points_plus_cash",
  "pay_scene",
  "payment_order",
  "member_open",
  "goods_cash",
  "cash_diff",
  "payNo",
  "payment_timeout_cancelled",
  "payment_callback_failed",
  "LFWIN",
  "paymentStatus",
  "cancelled",
  "CreateOrderRequest",
  "RefundId",
  "ExceptionId",
  "exception:write",
  "config:write",
  "product:write",
  "task:review",
  "withdraw:approve",
  "approval:request",
  "approval:review",
  "TGG_TASK_PLATFORM",
  "task_callback",
  "invite_commission",
  "order:fulfillment"
  ,
  "operation_ticket",
  "ticket:write",
  "customer:read"
];

for (const term of requiredTerms) {
  assert(content.includes(term), `OpenAPI missing term: ${term}`);
}

console.log("OpenAPI checks passed");
